[package]
name = "opa-wasm"
version = "0.1.0"
rust-version = "1.59"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"
default-run = "opa-eval"

[dependencies]
anyhow = "1.0.57"
base64 = "0.13.0"
clap = { version = "3.1.18", features = ["derive"], optional = true }
digest = "0.10.3"
hex = "0.4.3"
hmac = "0.12.1"
json-patch = "0.2.6"
md-5 = "0.10.1"
semver = "1.0.9"
serde = { version = "1.0.57", features = ["derive"] }
serde_json = "1.0.57"
sha1 = "0.10.1"
sha2 = "0.10.2"
sprintf = "0.1.2"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["sync", "macros"] }
tracing = "0.1.34"
tracing-forest = { version = "0.1.4", optional = true }
tracing-subscriber = { version = "0.3.11", features = [
  "env-filter",
], optional = true }
wasmtime = "0.37.0"

uuid = { version = "1", features = ["v4"] }

[dev-dependencies.tokio]
version = "1.18.2"
features = ["macros", "rt", "fs"]

[dev-dependencies]
flate2 = "1"
tar = "^0.4.38"
insta = { version = "1", features = ["redactions"] }
rstest = "0.15.0"

[features]
cli = [
  "clap",
  "tracing-forest",
  "tracing-subscriber",
  "tokio/fs",
  "tokio/rt-multi-thread",
]

[[bin]]
name = "opa-eval"
required-features = ["cli"]

[[bin]]
name = "simple"
required-features = ["cli"]
